FROM node:17-alpine3.12

# Create app directory
RUN mkdir -p /app
WORKDIR /app

ARG NEXT_PUBLIC_APP_VERSION
ENV NEXT_PUBLIC_APP_VERSION=${NEXT_PUBLIC_APP_VERSION}

# Installing dependencies
COPY package*.json /app
RUN npm i 

# Copying source files
COPY . /app

# Building app
RUN npm run build
EXPOSE 3000

CMD ["npm", "run", "start"]
